name: Compile on Release

on:
  release:
    types: [ published ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RELEASE_TAG: ${{ github.event.release.tag_name }}
    
permissions: 
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build executables
      run: ./compile.sh
      
    - name: Publish executables to GitHub Release
      uses: softprops/action-gh-release@v1
      if: startswith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: bin/*
